# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('lager', models.CharField(max_length=30)),
                ('pruefnummer', models.CharField(max_length=30)),
                ('seriennummer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('gewicht', models.CharField(max_length=30)),
                ('laenge', models.CharField(max_length=30)),
                ('leistung', models.CharField(max_length=30)),
                ('artikelnummer', models.CharField(max_length=30)),
                ('hersteller_lieferant', models.CharField(max_length=100)),
                ('preis_ek', models.CharField(max_length=30)),
                ('preis_vk', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='warengruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MaterialGroup'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Material'),
        ),
    ]
