# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170115_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='lager',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='artikelnummer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='gewicht',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='laenge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='leistung',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='preis_ek',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='preis_vk',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
