# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170115_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='preis_ek',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='preis_vk',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
