# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170115_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='preis_ek',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='preis_vk',
            field=models.IntegerField(),
        ),
    ]
